# Generated by Django 3.0.7 on 2020-09-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[
                ('testapp.parrot', 'parrot'),
                ('testapp.canine', 'canine'),
                ('testapp.feline', 'feline'),
                ('testapp.bigcat', 'big cat'),
                ('testapp.angrybigcat', 'angry big cat')
            ], db_index=True, max_length=255),
        ),
    ]
