# Generated by Django 3.0.7 on 2020-09-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200916_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wolf',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.canine',),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[
                ('testapp.parrot', 'parrot'),
                ('testapp.canine', 'canine'),
                ('testapp.wolf', 'wolf'),
                ('testapp.feline', 'feline'),
                ('testapp.bigcat', 'big cat'),
                ('testapp.angrybigcat', 'angry big cat')
            ], db_index=True, max_length=255),
        ),
    ]
