# Generated by Django 3.0.7 on 2020-09-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20200916_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('testapp.titledsource', 'titled source'), ('testapp.textualsource', 'textual source'), ('testapp.article', 'article')], db_index=True, max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('editors', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('volume', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextualSource',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.source',),
        ),
        migrations.CreateModel(
            name='TitledSource',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.source',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.textualsource', 'testapp.titledsource'),
        ),
    ]
