# Generated by Django 3.0.7 on 2020-09-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_article_source_textualsource_titledsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.textualsource',),
        ),
        migrations.AddField(
            model_name='source',
            name='end_page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='page_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('testapp.titledsource', 'titled source'), ('testapp.textualsource', 'textual source'), ('testapp.piece', 'piece'), ('testapp.article', 'article')], db_index=True, max_length=255),
        ),
    ]
